### PR TITLE
Add macintosh install instructions 💻

### PR DESCRIPTION
**Pull request by MichaelDimmitt**
Was able to get past the issues we were having on Thursday. See #2. 
Full disclosure: your go other repos, Jags and Limo work with no issues.

```bash
$ go version
$ go version go1.10.3 darwin/amd64 # output
```

This is the current error output when `make` is called.
```
[!] dependency not vendored: github.com/golang/protobuf/proto
[!] dependency not vendored: google.golang.org/genproto/googleapis/rpc/status
[!] dependency not vendored: github.com/golang/protobuf/ptypes/any
[!] dependency not vendored: github.com/golang/protobuf/ptypes/timestamp
[!] dependency not vendored: github.com/golang/protobuf/ptypes/duration
make: *** [vendorcheck] Error 1
```

### CODE REVIEW

**Comment by hoop33** [comment]
I'm trying to avoid putting Go installation instructions in the readme, since they can (and do) change and the Go team does a pretty good job of documenting them. And they're somewhat user-specific as well; your PR would work for `bash` users, for example, but not `zsh` or `fish` users. Also, you no longer need to set `$GOROOT` ( https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really ) -- you just need to set `$GOPATH` and add it to your path, as this link https://github.com/golang/go/wiki/SettingGOPATH outlines. Make sense?

**Comment by MichaelDimmitt** [comment]
@hoop33, I understand your intentions. not wanting to put go install instructions in the readme.

Ultimately this is your decision.
That being said there were links for the homebrew install,
Those that I do not have [brew instructions](https://gist.github.com/MichaelDimmitt/6b7d8801ec4d624fefc3e54a8a318c33)
modified to have the correct path from [here](https://gist.github.com/vsouza/77e6b20520d07652ed7d)

If I noticed Go documentation that had HomeBrew I would include that instead.
I looked at your additions in the readme and installation instructions have greatly improved.

I am going to update this pull request with a few changes like including `dep ensure -update`
That being said, it is okay with myself if you end up closing the pull request and make the changes locally. Expect my revised changes to this pull request within the next hour.

**Comment by hoop33** [comment]
What happens if you remove `$GOROOT` ?

**Comment by hoop33** [comment]
I just want to follow up on this, so we can close this out. What if we add, in step 3, an instruction to set `$GOPATH` and add `$GOPATH/bin` to your path? I don't want to link to that gist, because you don't need to set `$GOROOT` (you can unset it and then type `go env` to see that Go figures it out) -- what if you remove the `$GOROOT` entries from it?

**Comment by MichaelDimmitt** [comment]
Yesterday, I was removing $GOPATH and it stopped working.

Let me implement ‘go env’
Then I will make the change. 

Expect the resultant commit at 7pm.
As I am not currently in front of my computer.

**Comment by hoop33** [comment]
Interesting -- something weird is going on, because I don't have `$GOROOT` set and it works. And the link saying not to set it is from one of Go's maintainers. Let's get this figured out!

**Comment by MichaelDimmitt** [comment]
@hoop33, still works when you remove $GOROOT

**Comment by MichaelDimmitt** [comment]
@hoop33, I updated the commit.

**Comment by hoop33** [comment]
Sorry -- I've been on vacation. It looks like the commit still has `$GOROOT` and bash-specific instructions. I've added the `brew install protobuf` step -- how about I add in step 3 to add `GOPATH` and add it to your path, however is appropriate for your shell?

**Comment by MichaelDimmitt** [comment]
Confirmed, GOROOT not needed.
@hoop33, added a commit with the changes specified. 
```
# bashrc example: 
echo 'export GOPATH=$HOME/go; export PATH=$PATH:$GOPATH/bin' >> $HOME/.bashrc; . $HOME/.bashrc;
```

Additionally I noticed, 
`make && ./roster` was not working.
```
./roster
ts=2018-07-09T15:34:57.043407753Z tag=start msg="created logger"
ts=2018-07-09T15:34:57.043407753Z tag=start msg="failed to connect to database" err="pq: role \"password=\" does not exist"
```

However, this command does work,
`ROSTER_USER=<db user> ROSTER_PASSWORD=<db password> ./roster`

**Comment by hoop33** [comment]
Thanks!

**Pull request merged**
